# boardconfig.mk
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 33554432
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := exynos7884
TARGET_CPU_ABI := arm64-v8a

TW_THEME := portrait_hdpi
TW_EXTERNAL_STORAGE_PATH := /sdcard

# File system support
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_F2FS := true
TW_INCLUDE_NTFS := true
TW_INCLUDE_EXT4 := true
TW_INCLUDE_EXFAT := true

# Additional features
TW_USE_TOOLBOX := true
TW_INCLUDE_BLOB := true
TW_OEM_BUILD := true
TW_INCLUDE_TOYBOX := true
TW_INCLUDE_IMAGEFLASHER := true
TW_EXCLUDE_SUPERSU := true
TW_INCLUDE_REBOOT_MENU := true
TW_INCLUDE_APP_RESTORE := true

# USB and ADB
TW_INCLUDE_ADB := true
TW_INCLUDE_ADB_SIDELoad := true
TW_EXCLUDE_APP_STORAGE := true
TW_USE_ADB_SHELL := true
